# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ceaa50516926b06eb5026e9b26365ab85cb18e5f9303c76925fce3aea51b3e11d44bc48d802549af115ac907576a82e74d40ebf0ec24596b17c311f71031a54

test:
  secret_key_base: f49fc32c8aea090ef0f9c9e188891a83132a20a604f579d6786d9aced49045504c1d56032544236fbc0214e9e228d409e59f0b8bdb05771ece31f60d5cc37588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
